### ISSUE TITLE
New creation mode: combine

### ISSUE THREAD

**Issue by jaicab** [jaicab/sass-vary#7]
It has been suggested to have a creation mode where the "body class" (which will be now referred as class) got added to the selector. Here's an example:

``` sass
.js .foo{
    background: red;

    @include vary($create: combine) {
        background: vary-get('color-primary');
    }
}
```

Output:

``` css
.foo{
    background: red;    
}

.js .foo.is-user {
    background: blue;
}

.js .foo.is-admin {
    background: pink;
}

.js .foo.is-superadmin {
    background: black;
}
```

Although not recommended, could be useful for some. May be implementing this soon.
